FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MyConsult.Gateway/MyConsult.Gateway.csproj", "MyConsult.Gateway/"]
RUN dotnet restore "MyConsult.Gateway/MyConsult.Gateway.csproj"
COPY . .
WORKDIR "/src/MyConsult.Gateway"
RUN dotnet build "MyConsult.Gateway.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyConsult.Gateway.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
