FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MyConsult.Medical/MyConsult.Medical.csproj", "MyConsult.Medical/"]
RUN dotnet restore "MyConsult.Medical/MyConsult.Medical.csproj"
COPY . .
WORKDIR "/src/MyConsult.Medical"
RUN dotnet build "MyConsult.Insurance.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyConsult.Insurance.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet", "MyConsult.Insurance.dll" ]