FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MyConsult.MotorVehicle/MyConsult.MotorVehicle.csproj", "MyConsult.Medical/"]
RUN dotnet restore "MyConsult.Medical/MyConsult.Medical.csproj"
COPY . .
WORKDIR "/src/MyConsult.MotorVehicle"
RUN dotnet build "MyConsult.MotorVehicle.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyConsult.MotorVehicle.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet", "MyConsult.MotorVehicle.dll" ]